apiVersion: v1
kind: Service
metadata:
  name: {{.Values.application2.name}}
  labels:
    run: {{.Values.application2.name}}
spec:
  ports:
    - port: 8080
  selector:                               #labels inside the pod definition (in this case spec-template-metadata-labels
    app: {{.Values.application2.name}}
  type: ClusterIP
