apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.application2.name }}
  name: {{ .Values.application2.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.application2.name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.application2.name }}
    spec:
      containers:
        - image: {{ .Values.application2.image.repository }}
          name: {{ .Values.application2.name }}
          imagePullPolicy: {{ .Values.application2.image.pullPolicy }}
          resources: {}
          ports:
            - containerPort: 8080
status: {}